// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/progress-tracking/ProgressTracking.tsx": () => import("../components/mockups/progress-tracking/ProgressTracking.tsx")
};
